### PR TITLE
add implementation for label-studio annotations and DeepLabCut

### PR DESCRIPTION
**Pull request by quantumdot**
### Description
Add support for label-studio and DeepLabCut

#### Data Model Changes
- Fix equality of `Point`s. X and Y coordinates were previously compared using normal float equality semantics. Here we change to utilize the `numpy.isclose()` method for comparison, where two floats are compared for equality within some tolerance (we use just the default tolerances). Additionally, we will consider that two NaN values are equal, which is normally not true.
- Allow `Instance` objects to be compared for equality. The `points` collection within an instance are compared with the rule that both collections of points must contain the same set of nodes, and for each node the point must be equal according to the semantics described above.

#### Label Studio Support
- support for reading label-studio annotations from a file or `list[dict]` and conversion to `Labels` instance via `sleap_io.io.labelstudio.read_labels()` and `sleap_io.io.labelstudio.parse_tasks()`
- support conversion of `Labels` to `list[dict]` via `sleap_io.io.labelstudio.write_labels()`
- known issues:
    - label-studio uses relative coordinates (in the range 0-1), so writing label-studio tasks from a labels instance requires that the `Video` associated with a `LabeledFrame` properly implement the `Video.shape` property. If shape is not properly implemented, the label-studio tasks may not function properly. 

#### DeepLabCut Support (single- and multi-animal projects)
- support for reading DLC annotations and conversion to `Labels` instance via `sleap_io.io.dlc.load_dlc()` and  `sleap_io.io.dlc.dlc_to_labels()`.
- support conversion of `Labels` to DLC annotations via `sleap_io.io.dlc.write_dlc()` and `sleap_io.io.dlc.labels_to_dlc()`
- support determining if the DLC project is a _single-animal_ or a _multi-animal_ style project via `sleap_io.io.dlc.is_multianimal()`
- support loading `Skeleton` data from a DLC project via `sleap_io.io.dlc.load_skeletons()`
- known issues:
    - DLC does not include edges in their skeleton definitions, so a skeleton with only nodes and no edges is constructed.
    - Video data may not be properly implemented.
        - I think there is no way for us to know a video or image shape without us first loading it.
        - We currently only set the frame index for an annotation to zero. probably we can parse it from the filename?

### Types of changes

- [ ] Bugfix
- [x] New feature
- [ ] Refactor / Code style update (no logical changes)
- [ ] Build / CI changes
- [ ] Documentation Update
- [ ] Other (explain)

### Does this address any currently open issues?
[list open issues here]

### Outside contributors checklist

- [ ] Review the [guidelines for contributing](https://github.com/talmolab/sleap-io/blob/main/CONTRIBUTING.md) to this repository
- [ ] Add tests that prove your fix is effective or that your feature works
- [ ] Add necessary documentation (if appropriate)

#### Thank you for contributing to SLEAP-IO!
:heart:

### CODE REVIEW

**Comment by talmo** [comment]
Looking great @quantumdot! Feel free to mark this ready for review for @roomrys whenever you're done.

**Comment by quantumdot** [comment]
@talmo @roomrys I believe I have the bulk of functionality implemented for DLC and label-studio. Perhaps it is a good time to review changes?

We should also discuss Video instances, as some outstanding issues depend on the implementation details there.

**Comment by talmo** [comment]
> @talmo @roomrys I believe I have the bulk of functionality implemented for DLC and label-studio. Perhaps it is a good time to review changes?
> 
> We should also discuss Video instances, as some outstanding issues depend on the implementation details there.

Thanks! @roomrys can do the first review. Let's work around the `Video` stuff for now since that depends on the very unfinished branch at https://github.com/talmolab/sleap-io/tree/talmo/pims-video-backend.

**Comment by quantumdot** [comment]
CI / Tests are failing on `python==3.7` it seems due to pickle protocol version mismatch. See related: https://github.com/DeepLabCut/DLCutils/issues/19. Do you have a DLC dataset which works across the python version 3.8 boundary, where pickle version changed from 4 -> 5?

CI / Tests fail on windows `python==3.9` due to an import error for `pytables`. I don't understand why.

**Comment by quantumdot** [comment]
Closing this PR as it is superseded by the following (these changes split into three separate PRs based on separation of concerns)

- Changes to `Point` and `Instance` equality semantics: #21
- Add support for DeepLabCut projects: #25
- Add support for LabelStudio projects: #26

**Pull request closed without merging**
